import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { getTargetAdapter } from './target-adapters.js';
import type { AgentTarget, LoadedAgentSkill, RenderResult, TargetAdapter } from './types.js';

export class SkillRenderer {
  constructor(private readonly projectRoot = process.cwd()) {}

  async render(target: AgentTarget, skills: LoadedAgentSkill[]): Promise<RenderResult> {
    const adapter = getTargetAdapter(target);
    const filesWritten: string[] = [];
    const skippedSkills: string[] = [];
    for (const skill of skills) {
      if (!skill.manifest.compatibleTargets.includes(target)) {
        skippedSkills.push(skill.manifest.id);
        continue;
      }
      filesWritten.push(...await this.renderSkill(adapter, skill));
    }
    if (target === 'codex') filesWritten.push(await this.writeCodexAgentsMd(skills));
    return { target, filesWritten, skippedSkills };
  }

  private async renderSkill(adapter: TargetAdapter, skill: LoadedAgentSkill): Promise<string[]> {
    const skillContent = await readFile(skill.entryPath, 'utf-8');
    const rendered = `${this.generatedNotice(adapter, skill)}\n${skillContent}`;
    const files: string[] = [];
    if (adapter.supportsSkillFolder) {
      const skillPath = join(this.projectRoot, adapter.outputRoot, 'skills', skill.manifest.id, 'SKILL.md');
      await this.write(skillPath, rendered);
      files.push(skillPath);
    }
    if (adapter.supportsRules) {
      const rulePath = join(this.projectRoot, adapter.outputRoot, 'rules', `${skill.manifest.id}.md`);
      await this.write(rulePath, this.flattenForRule(skill, skillContent));
      files.push(rulePath);
    }
    if (adapter.supportsSteering) {
      const steeringPath = join(this.projectRoot, adapter.outputRoot, 'steering', `${skill.manifest.id}.md`);
      await this.write(steeringPath, this.flattenForRule(skill, skillContent));
      files.push(steeringPath);
    }
    if (adapter.supportsAgents) {
      const agentPath = join(this.projectRoot, adapter.outputRoot, 'agent', `${skill.manifest.id}.md`);
      await this.write(agentPath, this.flattenForRule(skill, skillContent));
      files.push(agentPath);
    }
    return files;
  }

  private async write(path: string, content: string): Promise<void> {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content, 'utf-8');
  }

  private generatedNotice(adapter: TargetAdapter, skill: LoadedAgentSkill): string {
    return [
      '<!--',
      `Generated by LUNOR from .agents/skills/${skill.manifest.category}/${skill.manifest.id}.`,
      `Target: ${adapter.id}. Do not edit generated files directly; edit the canonical skill instead.`,
      '-->',
    ].join('\n');
  }

  private flattenForRule(skill: LoadedAgentSkill, skillContent: string): string {
    return [
      `# ${skill.manifest.name}`,
      '',
      `Source: .agents/skills/${skill.manifest.category}/${skill.manifest.id}`,
      `Version: ${skill.manifest.version}`,
      '',
      '## Instructions',
      '',
      skillContent.replace(/^---[\s\S]*?---\s*/, '').trim(),
      '',
    ].join('\n');
  }

  private async writeCodexAgentsMd(skills: LoadedAgentSkill[]): Promise<string> {
    const path = join(this.projectRoot, 'AGENTS.md');
    const content = [
      '# AGENTS.md',
      '',
      'This repository uses LUNOR canonical skills from `.agents/skills`.',
      '',
      '## Active Skill Kits',
      '',
      ...skills.map(skill => `- ${skill.manifest.name} (${skill.manifest.id})`),
      '',
      '## Agent Rules',
      '',
      '- Edit canonical skills under `.agents/skills`; regenerate target files with `lunor skills sync --target codex`.',
      '- Do not run shell, network, browser, or MCP actions unless the relevant skill manifest grants that permission.',
      '- Preserve lower-kebab-case folder names and meaningful domain names.',
      '',
    ].join('\n');
    await writeFile(path, content, 'utf-8');
    return path;
  }
}
